-- ============================================================
-- RevPay: Loans table for admin loan verification module
-- ============================================================

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE loans (
            id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id         NUMBER NOT NULL,
            amount          NUMBER(12,2) NOT NULL,
            duration_months NUMBER NOT NULL,
            interest_rate   NUMBER(5,2),
            status          VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
            created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- Optional index on user_id for faster lookups
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_loans_user_id ON loans(user_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

